<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\PropertyRental.Application\PropertyRental.Application.csproj" />
      <ProjectReference Include="..\PropertyRental.Domain\PropertyRental.Domain.csproj" />
      <ProjectReference Include="..\PropertyRental.Infrastructure\PropertyRental.Infrastructure.csproj" />
    </ItemGroup>

</Project>
